<header class="admin-page-header"><div><p class="text-sm text-muted">Inbox</p><h1>Contact submissions</h1></div><div class="flex gap-2"><a class="filter-chip <?= $filter === 'all' ? 'is-active' : '' ?>" href="<?= e(url('/admin/contact-submissions')) ?>">All</a><a class="filter-chip <?= $filter === 'unread' ? 'is-active' : '' ?>" href="<?= e(url('/admin/contact-submissions?filter=unread')) ?>">Unread</a><a class="filter-chip <?= $filter === 'archived' ? 'is-active' : '' ?>" href="<?= e(url('/admin/contact-submissions?filter=archived')) ?>">Archived</a></div></header>
<div class="admin-inbox">
    <section class="admin-card p-0"><div class="divide-y divide-line"><?php foreach ($contacts as $item): ?><a class="block p-5 hover:bg-blush/30 <?= $selected && (int) $selected['id'] === (int) $item['id'] ? 'bg-blush/50' : '' ?>" href="<?= e(url('/admin/contact-submissions?filter=' . $filter . '&view=' . $item['id'])) ?>"><div class="flex items-center gap-2"><p class="font-semibold text-wine"><?= e($item['name']) ?></p><?php if (!$item['is_read']): ?><span class="size-2 rounded-full bg-berry"></span><?php endif; ?><time class="ml-auto text-xs text-muted"><?= e(format_date($item['created_at'], 'M j')) ?></time></div><p class="mt-1 text-xs text-muted"><?= e($item['topic'] ?: 'General enquiry') ?> · <?= e($item['email']) ?></p><p class="mt-2 truncate text-sm text-muted"><?= e($item['message']) ?></p></a><?php endforeach; ?><?php if (!$contacts): ?><div class="empty-state m-5">No submissions in this view.</div><?php endif; ?></div></section>
    <section class="admin-card">
        <?php if ($selected): ?>
            <div class="admin-card-header"><div><p class="text-xs font-bold uppercase tracking-[.12em] text-muted"><?= e($selected['topic'] ?: 'General enquiry') ?></p><h2 class="mt-1"><?= e($selected['name']) ?></h2></div><time class="text-xs text-muted"><?= e(format_date($selected['created_at'], 'M j, Y · g:i A')) ?></time></div>
            <dl class="mt-6 grid gap-4 rounded-xl bg-[#FAF6F4] p-5 text-sm sm:grid-cols-2"><div><dt class="font-bold text-wine">Email</dt><dd class="mt-1 text-muted"><a href="mailto:<?= e($selected['email']) ?>"><?= e($selected['email']) ?></a></dd></div><div><dt class="font-bold text-wine">Phone</dt><dd class="mt-1 text-muted"><?= e($selected['phone'] ?: 'Not provided') ?></dd></div><div><dt class="font-bold text-wine">Consent recorded</dt><dd class="mt-1 text-muted"><?= e(format_date($selected['consented_at'], 'M j, Y · g:i A')) ?></dd></div><div><dt class="font-bold text-wine">Source</dt><dd class="mt-1 text-muted"><?= e($selected['source_page']) ?></dd></div></dl>
            <div class="mt-7 whitespace-pre-wrap leading-8 text-muted"><?= e($selected['message']) ?></div>
            <div class="mt-8 flex flex-wrap gap-2">
                <a class="button button-primary" href="mailto:<?= e($selected['email']) ?>">Reply by email</a>
                <?php if ($selected['phone']): ?><a class="button button-secondary" href="https://wa.me/<?= e(preg_replace('/\D+/', '', $selected['phone'])) ?>" target="_blank" rel="noopener">WhatsApp</a><?php endif; ?>
                <form method="post" action="<?= e(url('/admin/contact-submissions')) ?>"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int) $selected['id'] ?>"><button class="button button-secondary" name="action" value="unread">Mark unread</button></form>
                <form method="post" action="<?= e(url('/admin/contact-submissions')) ?>"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int) $selected['id'] ?>"><button class="button button-secondary" name="action" value="archive">Archive</button></form>
                <form method="post" action="<?= e(url('/admin/contact-submissions')) ?>"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int) $selected['id'] ?>"><button class="button button-danger" name="action" value="delete" data-confirm="Permanently delete this submission?">Delete</button></form>
            </div>
        <?php else: ?><div class="empty-state">Select a submission to read it.</div><?php endif; ?>
    </section>
</div>

