<?php $event = $editing ?: ['id'=>'','title'=>'','slug'=>'','excerpt'=>'','description'=>'','event_date'=>'','event_end'=>'','timezone'=>'Africa/Lagos','location_mode'=>'physical','location'=>'','event_type'=>'Community Event','external_link'=>'','cover_image'=>'','cover_alt'=>'','is_featured'=>0,'status'=>'draft','seo_title'=>'','seo_description'=>'']; ?>
<header class="admin-page-header"><div><p class="text-sm text-muted">Content management</p><h1>Events</h1></div><a class="button button-primary" href="<?= e(url('/admin/events?new=1')) ?>">+ New event</a></header>

<div class="admin-split">
    <section class="admin-card min-w-0">
        <form method="get" action="<?= e(url('/admin/events')) ?>" class="mb-5 flex gap-2"><input class="form-control" name="q" value="<?= e($search) ?>" placeholder="Search events"><button class="button button-secondary">Search</button></form>
        <div class="space-y-3">
            <?php foreach ($events as $item): ?>
                <a class="admin-list-card <?= (int) ($event['id'] ?: 0) === (int) $item['id'] ? 'is-active' : '' ?>" href="<?= e(url('/admin/events?edit=' . $item['id'])) ?>">
                    <img src="<?= e(media_url($item['cover_image'])) ?>" alt="" class="size-16 rounded-xl object-cover">
                    <div class="min-w-0 flex-1"><div class="flex gap-2"><span class="chip"><?= e($item['event_type']) ?></span><?php if ($item['is_featured']): ?><span class="chip chip-featured">Featured</span><?php endif; ?></div><p class="mt-2 truncate font-semibold text-wine"><?= e($item['title']) ?></p><p class="mt-1 text-xs text-muted"><?= e(format_date($item['event_date'])) ?> · <?= e($item['location']) ?></p></div>
                    <span class="status status-<?= e($item['status']) ?>"><?= e($item['status']) ?></span>
                </a>
            <?php endforeach; ?>
            <?php if (!$events): ?><div class="empty-state">No events match this search.</div><?php endif; ?>
        </div>
    </section>

    <section class="admin-card">
        <div class="admin-card-header"><div><p class="text-xs font-bold uppercase tracking-[.12em] text-muted"><?= $event['id'] ? 'Edit event' : 'Create event' ?></p><h2 class="mt-1"><?= e($event['title'] ?: 'New event') ?></h2></div><?php if ($event['id']): ?><a class="text-sm font-semibold text-wine" href="<?= e(url('/events/' . $event['slug'])) ?>" target="_blank" rel="noopener">Preview ↗</a><?php endif; ?></div>
        <form method="post" enctype="multipart/form-data" action="<?= e(url('/admin/events')) ?>" class="mt-6 space-y-7" data-unsaved-form>
            <?= csrf_field() ?><input type="hidden" name="id" value="<?= e($event['id']) ?>">
            <div class="form-grid"><div class="form-field md:col-span-2"><label>Title <span>*</span></label><input class="form-control" name="title" value="<?= e($event['title']) ?>" required></div><div class="form-field"><label>Slug</label><input class="form-control" name="slug" value="<?= e($event['slug']) ?>"></div><div class="form-field"><label>Event type</label><select class="form-control" name="event_type"><?php foreach (['Community Event','Workshop','Grant Program'] as $type): ?><option <?= $event['event_type'] === $type ? 'selected' : '' ?>><?= e($type) ?></option><?php endforeach; ?></select></div><div class="form-field md:col-span-2"><label>Short excerpt <span>*</span></label><textarea class="form-control min-h-24" name="excerpt" required><?= e($event['excerpt']) ?></textarea></div></div>
            <div class="form-field"><label>Full description</label><div class="rich-toolbar" data-rich-toolbar><button type="button" data-tag="h2">Heading</button><button type="button" data-tag="strong">Bold</button><button type="button" data-tag="ul">List</button><button type="button" data-tag="p">Paragraph</button></div><textarea class="form-control min-h-60 font-mono text-sm" name="description" data-rich-text><?= e($event['description']) ?></textarea></div>
            <div class="form-grid"><div class="form-field"><label>Start date & time</label><input class="form-control" type="datetime-local" name="event_date" value="<?= e($event['event_date'] ? str_replace(' ', 'T', substr($event['event_date'], 0, 16)) : '') ?>"></div><div class="form-field"><label>End date & time</label><input class="form-control" type="datetime-local" name="event_end" value="<?= e($event['event_end'] ? str_replace(' ', 'T', substr($event['event_end'], 0, 16)) : '') ?>"></div><div class="form-field"><label>Timezone</label><input class="form-control" name="timezone" value="<?= e($event['timezone']) ?>"></div><div class="form-field"><label>Location mode</label><select class="form-control" name="location_mode"><?php foreach (['physical','online','hybrid'] as $mode): ?><option <?= $event['location_mode'] === $mode ? 'selected' : '' ?> value="<?= e($mode) ?>"><?= e(ucfirst($mode)) ?></option><?php endforeach; ?></select></div><div class="form-field"><label>Location</label><input class="form-control" name="location" value="<?= e($event['location']) ?>"></div><div class="form-field"><label>External link</label><input class="form-control" type="url" name="external_link" value="<?= e($event['external_link']) ?>"></div></div>
            <fieldset class="admin-fieldset"><legend>Cover image</legend><?php if ($event['cover_image']): ?><img src="<?= e(media_url($event['cover_image'])) ?>" alt="" class="mb-4 aspect-video w-full rounded-xl object-cover"><?php endif; ?><div class="form-grid"><div class="form-field"><label>Upload image</label><input class="file-control" type="file" name="cover_image" accept="image/jpeg,image/png,image/webp"></div><div class="form-field"><label>Or image URL</label><input class="form-control" type="url" name="cover_url" value="<?= e($event['cover_image']) ?>"></div><div class="form-field md:col-span-2"><label>Alt text <span>*</span></label><input class="form-control" name="cover_alt" value="<?= e($event['cover_alt']) ?>" required></div></div></fieldset>
            <fieldset class="admin-fieldset"><legend>Gallery</legend><?php if ($gallery): ?><div class="mb-4 grid grid-cols-3 gap-3"><?php foreach ($gallery as $image): ?><figure><img class="aspect-square rounded-lg object-cover" src="<?= e(media_url($image['image_path'])) ?>" alt="<?= e($image['alt_text']) ?>"><figcaption class="mt-1 text-xs text-muted"><?= e($image['alt_text']) ?></figcaption></figure><?php endforeach; ?></div><?php endif; ?><div class="form-field"><label>Add images</label><input class="file-control" type="file" name="gallery[]" accept="image/jpeg,image/png,image/webp" multiple><p class="field-help">Add matching alt text lines below, in the same order.</p><textarea class="form-control mt-2" name="gallery_alt[]" placeholder="Describe the uploaded image"></textarea></div></fieldset>
            <fieldset class="admin-fieldset"><legend>Search and publishing</legend><div class="form-grid"><div class="form-field"><label>SEO title</label><input class="form-control" name="seo_title" value="<?= e($event['seo_title']) ?>"></div><div class="form-field"><label>Status</label><select class="form-control" name="status"><option value="draft" <?= $event['status'] === 'draft' ? 'selected' : '' ?>>Draft</option><option value="published" <?= $event['status'] === 'published' ? 'selected' : '' ?>>Published</option></select></div><div class="form-field md:col-span-2"><label>SEO description</label><textarea class="form-control" name="seo_description"><?= e($event['seo_description']) ?></textarea></div><label class="consent-row md:col-span-2"><input type="checkbox" name="is_featured" value="1" <?= $event['is_featured'] ? 'checked' : '' ?>><span>Feature this event on the homepage</span></label></div></fieldset>
            <div class="admin-savebar"><button class="button button-primary" name="action" value="save">Save event</button><?php if ($event['id']): ?><button class="button button-danger ml-auto" name="action" value="delete" data-confirm="Delete this event and its gallery? This cannot be undone.">Delete</button><?php endif; ?></div>
        </form>
    </section>
</div>

