<?php $slide = $editing ?: ['id'=>'','image_path'=>'','image_alt'=>'','headline'=>'','subheading'=>'','cta_label'=>'Make an appointment','cta_link'=>'/appointment','secondary_label'=>'','secondary_link'=>'','sort_order'=>0,'is_active'=>1]; ?>
<header class="admin-page-header"><div><p class="text-sm text-muted">Homepage</p><h1>Hero slides</h1></div><a class="button button-primary" href="<?= e(url('/admin/hero-slides?new=1')) ?>">+ Add slide</a></header>
<?php if ((int) query_value('SELECT COUNT(*) FROM hero_slides WHERE is_active = 1') === 0): ?><div class="mb-6 rounded-xl border border-amber/30 bg-[#FFF7EB] p-4 text-sm text-muted"><strong class="text-wine">No active slides.</strong> The homepage will show its built-in safe fallback until a slide is activated.</div><?php endif; ?>
<div class="admin-split">
    <section class="admin-card"><div class="space-y-3"><?php foreach ($slides as $item): ?><a class="admin-list-card <?= (int) ($slide['id'] ?: 0) === (int) $item['id'] ? 'is-active' : '' ?>" href="<?= e(url('/admin/hero-slides?edit=' . $item['id'])) ?>"><?php if ($item['image_path']): ?><img src="<?= e(media_url($item['image_path'])) ?>" alt="" class="h-16 w-24 rounded-xl object-cover"><?php else: ?><span class="grid h-16 w-24 shrink-0 place-items-center rounded-xl bg-blush text-xs font-bold text-wine">No image</span><?php endif; ?><div class="min-w-0 flex-1"><p class="truncate font-semibold text-wine"><?= e($item['headline']) ?></p><p class="mt-1 text-xs text-muted">Order <?= (int) $item['sort_order'] ?></p></div><span class="status <?= $item['is_active'] ? 'status-published' : 'status-draft' ?>"><?= $item['is_active'] ? 'Active' : 'Inactive' ?></span></a><?php endforeach; ?></div></section>
    <section class="admin-card">
        <div class="admin-card-header"><h2><?= $slide['id'] ? 'Edit slide' : 'Create slide' ?></h2><?php if ($slide['id']): ?><a href="<?= e(url('/')) ?>" target="_blank" class="text-sm font-semibold text-wine">Preview homepage ↗</a><?php endif; ?></div>
        <form method="post" enctype="multipart/form-data" action="<?= e(url('/admin/hero-slides')) ?>" class="mt-6 space-y-6" data-unsaved-form>
            <?= csrf_field() ?><input type="hidden" name="id" value="<?= e($slide['id']) ?>">
            <?php if ($slide['image_path']): ?><img src="<?= e(media_url($slide['image_path'])) ?>" alt="" class="aspect-[16/9] w-full rounded-xl object-cover"><?php endif; ?>
            <div class="form-grid"><div class="form-field"><label>Upload hero image</label><input class="file-control" type="file" name="image" accept="image/jpeg,image/png,image/webp"></div><div class="form-field"><label>Or image path / URL</label><input class="form-control" type="text" name="image_url" value="<?= e($slide['image_path']) ?>" placeholder="/uploads/… or https://…"></div><div class="form-field md:col-span-2"><label>Image alt text</label><input class="form-control" name="image_alt" value="<?= e($slide['image_alt']) ?>"><p class="field-help">Required when an image is present.</p></div><?php if ($slide['image_path']): ?><label class="consent-row md:col-span-2"><input type="checkbox" name="remove_image" value="1"><span>Remove this image and deactivate the slide</span></label><?php endif; ?><div class="form-field md:col-span-2"><label>Headline <span>*</span></label><input class="form-control" name="headline" value="<?= e($slide['headline']) ?>" required></div><div class="form-field md:col-span-2"><label>Subheading</label><textarea class="form-control" name="subheading"><?= e($slide['subheading']) ?></textarea></div><div class="form-field"><label>Primary CTA label</label><input class="form-control" name="cta_label" value="<?= e($slide['cta_label']) ?>"></div><div class="form-field"><label>Primary CTA link</label><input class="form-control" name="cta_link" value="<?= e($slide['cta_link']) ?>"></div><div class="form-field"><label>Secondary CTA label</label><input class="form-control" name="secondary_label" value="<?= e($slide['secondary_label']) ?>"></div><div class="form-field"><label>Secondary CTA link</label><input class="form-control" name="secondary_link" value="<?= e($slide['secondary_link']) ?>"></div><div class="form-field"><label>Sort order</label><input class="form-control" type="number" name="sort_order" value="<?= e($slide['sort_order']) ?>"></div><label class="consent-row self-end"><input type="checkbox" name="is_active" value="1" <?= $slide['is_active'] ? 'checked' : '' ?>><span>Active on homepage (requires an image)</span></label></div>
            <div class="admin-savebar"><button class="button button-primary" name="action" value="save">Save slide</button><?php if ($slide['id']): ?><button class="button button-danger ml-auto" name="action" value="delete" data-confirm="Delete this hero slide?">Delete</button><?php endif; ?></div>
        </form>
    </section>
</div>
