<?php $service = $editing ?: ['id'=>'','title'=>'','slug'=>'','excerpt'=>'','description'=>'','cover_image'=>'','cover_alt'=>'','sort_order'=>0,'is_pinned'=>0,'status'=>'draft','seo_title'=>'','seo_description'=>'']; ?>
<header class="admin-page-header"><div><p class="text-sm text-muted">Content management</p><h1>Services</h1></div><a class="button button-primary" href="<?= e(url('/admin/services?new=1')) ?>">+ New service</a></header>
<div class="admin-split">
    <section class="admin-card"><div class="space-y-3"><?php foreach ($services as $item): ?><a class="admin-list-card <?= (int) ($service['id'] ?: 0) === (int) $item['id'] ? 'is-active' : '' ?>" href="<?= e(url('/admin/services?edit=' . $item['id'])) ?>"><?php if ($item['cover_image']): ?><img src="<?= e(media_url($item['cover_image'])) ?>" alt="" class="size-16 rounded-xl object-cover"><?php else: ?><span class="grid size-16 shrink-0 place-items-center rounded-xl bg-blush text-xs font-bold text-wine">No image</span><?php endif; ?><div class="min-w-0 flex-1"><p class="truncate font-semibold text-wine"><?= e($item['title']) ?></p><p class="mt-1 truncate text-xs text-muted">Order <?= (int) $item['sort_order'] ?> · <?= $item['is_pinned'] ? 'Pinned' : 'Standard' ?></p></div><span class="status status-<?= e($item['status']) ?>"><?= e($item['status']) ?></span></a><?php endforeach; ?></div></section>
    <section class="admin-card">
        <div class="admin-card-header"><div><p class="text-xs font-bold uppercase tracking-[.12em] text-muted"><?= $service['id'] ? 'Edit service' : 'Create service' ?></p><h2 class="mt-1"><?= e($service['title'] ?: 'New service') ?></h2></div><?php if ($service['id']): ?><a class="text-sm font-semibold text-wine" href="<?= e(url('/services/' . $service['slug'])) ?>" target="_blank" rel="noopener">Preview ↗</a><?php endif; ?></div>
        <form method="post" enctype="multipart/form-data" action="<?= e(url('/admin/services')) ?>" class="mt-6 space-y-7" data-unsaved-form>
            <?= csrf_field() ?><input type="hidden" name="id" value="<?= e($service['id']) ?>">
            <div class="form-grid"><div class="form-field md:col-span-2"><label>Title <span>*</span></label><input class="form-control" name="title" value="<?= e($service['title']) ?>" required></div><div class="form-field"><label>Slug</label><input class="form-control" name="slug" value="<?= e($service['slug']) ?>"></div><div class="form-field"><label>Display order</label><input class="form-control" type="number" name="sort_order" value="<?= e($service['sort_order']) ?>"></div><div class="form-field md:col-span-2"><label>Short excerpt <span>*</span></label><textarea class="form-control min-h-24" name="excerpt" maxlength="320" required><?= e($service['excerpt']) ?></textarea></div></div>
            <div class="form-field"><label>Full description</label><div class="rich-toolbar" data-rich-toolbar><button type="button" data-tag="h2">Heading</button><button type="button" data-tag="strong">Bold</button><button type="button" data-tag="ul">List</button><button type="button" data-tag="p">Paragraph</button></div><textarea class="form-control min-h-60 font-mono text-sm" name="description" data-rich-text><?= e($service['description']) ?></textarea></div>
            <fieldset class="admin-fieldset">
                <legend>Media</legend>
                <?php if ($service['cover_image']): ?><img src="<?= e(media_url($service['cover_image'])) ?>" alt="" class="mb-4 aspect-video w-full rounded-xl object-cover"><?php endif; ?>
                <div class="form-grid">
                    <div class="form-field"><label>Upload cover <span class="text-muted">(optional)</span></label><input class="file-control" type="file" name="cover_image" accept="image/jpeg,image/png,image/webp"></div>
                    <div class="form-field"><label>Or image path / URL</label><input class="form-control" type="text" name="cover_url" value="<?= e($service['cover_image']) ?>" placeholder="/uploads/… or https://…"></div>
                    <div class="form-field md:col-span-2"><label>Cover alt text</label><input class="form-control" name="cover_alt" value="<?= e($service['cover_alt']) ?>"><p class="field-help">Required only when a cover image is present.</p></div>
                    <?php if ($service['cover_image']): ?><label class="consent-row md:col-span-2"><input type="checkbox" name="remove_cover" value="1"><span>Remove the cover image from this service</span></label><?php endif; ?>
                    <div class="form-field"><label>Add a gallery image</label><input class="file-control" type="file" name="gallery[]" accept="image/jpeg,image/png,image/webp"><p class="field-help">Save once per image so each upload has accurate alt text.</p></div>
                    <div class="form-field"><label>Gallery alt text</label><input class="form-control" name="gallery_alt[]" placeholder="Describe the uploaded image"></div>
                </div>
                <?php if ($gallery): ?><div class="mt-5 grid gap-3 sm:grid-cols-2"><?php foreach ($gallery as $media): ?><label class="rounded-xl border border-line bg-ivory p-3"><img src="<?= e(media_url($media['image_path'])) ?>" alt="" class="aspect-video w-full rounded-lg object-cover"><span class="consent-row mt-3"><input type="checkbox" name="remove_gallery[]" value="<?= (int) $media['id'] ?>"><span>Remove this gallery image</span></span></label><?php endforeach; ?></div><?php endif; ?>
            </fieldset>
            <fieldset class="admin-fieldset"><legend>Search and publishing</legend><div class="form-grid"><div class="form-field"><label>SEO title</label><input class="form-control" name="seo_title" value="<?= e($service['seo_title']) ?>"></div><div class="form-field"><label>Status</label><select class="form-control" name="status"><option value="draft" <?= $service['status'] === 'draft' ? 'selected' : '' ?>>Draft</option><option value="published" <?= $service['status'] === 'published' ? 'selected' : '' ?>>Published</option></select></div><div class="form-field md:col-span-2"><label>SEO description</label><textarea class="form-control" name="seo_description"><?= e($service['seo_description']) ?></textarea></div><label class="consent-row md:col-span-2"><input type="checkbox" name="is_pinned" value="1" <?= $service['is_pinned'] ? 'checked' : '' ?>><span>Pin this service in public previews</span></label></div></fieldset>
            <div class="admin-savebar"><button class="button button-primary" name="action" value="save">Save service</button><?php if ($service['id']): ?><button class="button button-danger ml-auto" name="action" value="delete" data-confirm="Delete this service and its gallery?">Delete</button><?php endif; ?></div>
        </form>
    </section>
</div>
