<?php $testimonial = $editing ?: ['id'=>'','client_name'=>'','photo_path'=>'','photo_alt'=>'','quote'=>'','sort_order'=>0,'is_visible'=>1]; ?>
<header class="admin-page-header"><div><p class="text-sm text-muted">Homepage stories</p><h1>Testimonials</h1></div><a class="button button-primary" href="<?= e(url('/admin/testimonials?new=1')) ?>">+ Add testimonial</a></header>
<div class="admin-split">
    <section class="admin-card"><div class="space-y-3"><?php foreach ($testimonials as $item): ?><a class="admin-list-card <?= (int) ($testimonial['id'] ?: 0) === (int) $item['id'] ? 'is-active' : '' ?>" href="<?= e(url('/admin/testimonials?edit=' . $item['id'])) ?>"><?php if ($item['photo_path']): ?><img src="<?= e(media_url($item['photo_path'])) ?>" alt="" class="size-14 rounded-full object-cover"><?php else: ?><span class="grid size-14 place-items-center rounded-full bg-blush font-bold text-wine"><?= e(mb_substr($item['client_name'], 0, 1)) ?></span><?php endif; ?><div class="min-w-0 flex-1"><p class="font-semibold text-wine"><?= e($item['client_name']) ?></p><p class="mt-1 truncate text-xs text-muted"><?= e($item['quote']) ?></p></div><span class="status <?= $item['is_visible'] ? 'status-published' : 'status-draft' ?>"><?= $item['is_visible'] ? 'Visible' : 'Hidden' ?></span></a><?php endforeach; ?></div></section>
    <section class="admin-card">
        <div class="admin-card-header"><h2><?= $testimonial['id'] ? 'Edit testimonial' : 'Add testimonial' ?></h2></div>
        <form method="post" enctype="multipart/form-data" action="<?= e(url('/admin/testimonials')) ?>" class="mt-6 space-y-6" data-unsaved-form>
            <?= csrf_field() ?><input type="hidden" name="id" value="<?= e($testimonial['id']) ?>">
            <?php if ($testimonial['photo_path']): ?><img src="<?= e(media_url($testimonial['photo_path'])) ?>" alt="" class="size-28 rounded-2xl object-cover"><?php endif; ?>
            <div class="form-grid"><div class="form-field md:col-span-2"><label>Client name <span>*</span></label><input class="form-control" name="client_name" value="<?= e($testimonial['client_name']) ?>" required></div><div class="form-field"><label>Upload photo</label><input class="file-control" type="file" name="photo" accept="image/jpeg,image/png,image/webp"></div><div class="form-field"><label>Or photo URL</label><input class="form-control" type="url" name="photo_url" value="<?= e($testimonial['photo_path']) ?>"></div><div class="form-field md:col-span-2"><label>Photo alt text</label><input class="form-control" name="photo_alt" value="<?= e($testimonial['photo_alt']) ?>"></div><div class="form-field md:col-span-2"><label>Quote <span>*</span></label><textarea class="form-control min-h-40" name="quote" maxlength="800" required><?= e($testimonial['quote']) ?></textarea></div><div class="form-field"><label>Display order</label><input class="form-control" type="number" name="sort_order" value="<?= e($testimonial['sort_order']) ?>"></div><label class="consent-row self-end"><input type="checkbox" name="is_visible" value="1" <?= $testimonial['is_visible'] ? 'checked' : '' ?>><span>Visible on homepage</span></label></div>
            <div class="admin-savebar"><button class="button button-primary" name="action" value="save">Save testimonial</button><?php if ($testimonial['id']): ?><button class="button button-danger ml-auto" name="action" value="delete" data-confirm="Delete this testimonial?">Delete</button><?php endif; ?></div>
        </form>
    </section>
</div>

