<section class="page-hero"><div class="mx-auto max-w-4xl px-5 py-20"><p class="eyebrow">Your information</p><h1 class="page-title mt-5">Privacy policy</h1><p class="mt-6 text-lg leading-8 text-muted">How information submitted through this website is collected, used, and protected.</p></div></section>
<section class="section bg-white"><article class="prose-warm prose-large mx-auto max-w-4xl px-5">
    <h2>Information we collect</h2><p>We collect information you choose to provide through contact, appointment, grant-application, and newsletter forms. This may include your name, contact details, enquiry, preferred appointment information, structured grant-application answers, and grant documents you choose to upload.</p>
    <h2>How information is used</h2><p>Information is used to respond to enquiries, arrange requested sessions, manage events and grants, administer community updates, and maintain records required for those activities.</p>
    <h2>Payments and transactional email</h2><p>When online appointment payment is enabled, the website sends your email address, payment amount, currency, and a unique booking reference to Paystack so payment can be processed and verified. EMB Chronicles does not receive or store your card or bank credentials. Transactional confirmation emails are delivered through the SMTP provider configured by the site administrator.</p>
    <h2>Access and retention</h2><p>Administrative access is restricted by role. Grant documents are stored outside the public website and are available only to authorised grant reviewers. Access to those documents is recorded. Records should be retained only as long as reasonably necessary for the purpose they were submitted or as required by applicable obligations.</p>
    <h2>Your choices</h2><p>You may request correction or deletion of information by contacting <?= e(setting('email')) ?>. Some information may need to be retained where an applicable obligation requires it.</p>
    <h2>Health information</h2><p>This website is not an emergency or clinical-record system. Do not submit urgent medical information. Contact your licensed medical team or local emergency services where appropriate.</p>
</article></section>
